# Generated by Django 4.1.3 on 2022-11-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partner_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
